### ISSUE TITLE
Unused options for pydevproject: 'name'

### ISSUE THREAD

**Issue by yucer** [acsone/acsone.recipe.odoo.pydev#7]
Following the instructions of https://testpypi.python.org/pypi/acsone.recipe.odoo.pydev/2.0 
I am using this:

```INI
[buildout]
extends = buildout.cfg
parts = pydevproject

[pydevproject]
<= openerp
recipe = acsone.recipe.odoo.pydev
version = path /opt/odoo/lib/server/HEAD/
name = myname
python-version = python 2.7
python-interpreter = Default
```
but it seems that my name for the project is ignored.

**Comment by lmignon** [comment]
You're right `name` is ignored but not `project-name` Replace `name` by `project-name`. I'll fix the documentation. Sorry.

**Comment by yucer** [comment]
No problem. Thanks to you. :-)

**Comment by yucer** [comment]
Is the name of the project supposed to be used in the file names of the `/bin` scripts?

I get still `python_pydevproject`, `start_pydevproject`, etc...

**Comment by lmignon** [comment]
@yucer no, the name is only used as name of your project when importing the project into eclipse. Script's name are generated using the part name in your buildout.

``` ini
[pydevproject]
<= openerp
```

-> `python_pydevproject`, `start_pydevproject`, etc...
You can control the names of the startup scripts with the openerp_scripts option. See the documentation http://pythonhosted.org/anybox.recipe.odoo/scripts.html#startup-scripts
